# This file will hold any hard configurations MailCannon may need. Customizations included.

# When creating a MailCannon::Envelope the default behavior is to auto-post the Job to send it.
auto_post: <%=ENV['auto_post']%>

# This is will schedule a delay for the Job execution, useful if you want to be able to Cancel the Job.
waiting_time: <%=ENV['waiting_time']%>

# Destroy mail content after send was successful, all other Envelope data is left untouched.
# * this config is useful for saving storage
auto_destroy: <%=ENV['auto_destroy']%>

# MailCannon builds the 'name' substitution Array for convenience, using the name from Envelope.to: [{email: 'foo', name: 'bar'}]
default_name_placeholder: <%=ENV['default_name_placeholder']%>

# MailCannon builds the 'email' substitution Array for convenience, using the email from Envelope.to: [{email: 'foo', name: 'bar'}]
default_email_placeholder: <%=ENV['default_email_placeholder']%>

# Pretty self explanatory. This is intended to be used by your event consuming service.
add_envelope_id_to_unique_args: <%=ENV['add_envelope_id_to_unique_args']%>

# Pretty self explanatory. This is intended to be used by your event consuming service.
add_envelope_bag_id_to_unique_args: <%=ENV['add_envelope_bag_id_to_unique_args']%>
