production:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      options:
        write:
          w: 1
staging:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      options:
        write:
          w: 1
development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      options:
        write:
          w: 1
